### ISSUE TITLE
Model Evaluation Clarification for MPIIFaceGaze Dataset

### ISSUE THREAD

**Issue by Zeleni9** [yakhyo/gaze-estimation#6]
First, thank you for maintaining this repository. The code is well-organized and clear.

### Current Understanding
1. I've downloaded the `gaze360.pkl` model from the original L2CSNet repository.
2. I've visualized the `resnet50.pt` model from this repository.
3. For MPIIFaceGaze evaluation, the correct number of bins for the classification part is required:
   - Gaze360 model: 90 bins
   - MPIIFaceGaze: 28 bins

### Questions
1. **Model Training:** To evaluate the downloaded models on MPIIFaceGaze, do I need to train a new model with a different bin configuration (28 bins instead of 90)?

2. **Reported MAE:** The original paper states an MAE of 3.9-4.0 degrees. Do you know:
   a) Is this MAE the result of evaluation on the full dataset?
   b) Or is it from a leave-one-out evaluation setting?

Thank you for your time and assistance! 🔥

**Comment by yakhyo** [comment]
Hi @Zeleni9 , thank you for your kind words.

I trained all the models on Gaze360 dataset. So there is different bin size for each dataset because of the angle range in each dataset. Gaze360 has more bins which allows to use it on a different dataset which has smaller number of bins. 

A1: It should be possible to use the trained model on Gaze360 and evaluate it on MPIIFaceGaze with some modifications in `evaluate.py`. I do not think you need to train the model from scratch for MPIIFaceGaze.  (let me know if you could do it)

A2: I exactly do not have answer on this. But when I was trying to reproduce training code (L2CSNet) for MPIIFaceGaze dataset, I saw it was k-fold cross-validation.
